### PR TITLE
Added more unit tests and fixed them

### PR DESCRIPTION
**Pull request by ehoogerbeets**
- works better than the initial version with less false positives
- correctly shows warnings for most of Box's xliff files in React projects
- still more work to do for loading plugins and creating the plugins for other project types (python, android, ios, etc.)

### CODE REVIEW

**Comment by ehoogerbeets** [comment]
The `init` branch needs to be merged first, and then this one

**Comment by ehoogerbeets** [comment]
@gouniLee Okay, rebased. Now you can review!

**Comment by gouniLee** [comment]
When I reviewer #PR1, it was ok when `node src/index.js`
but In this PR, it doesn't. Should I give an additional parameter?
```
> node src/index.js 
> INFO: i18nlint - Copyright (c) 2022 JEDLsoft, All rights reserved.
```

**Comment by ehoogerbeets** [comment]
Okay, that is fixed now too

**Review by gouniLee — APPROVED** [review]

**Pull request merged**
